from typing import ClassVar


class BaseProxyError(Exception):
    """
    Base class for errors generated by the portal itself, as opposed to
    error responses returned by the proxied server.
    """

    http_status: ClassVar[int]
    title: ClassVar[str]
    # Keep the tone of the explanations consistent with the parallel
    # line in templates/proxy/server-error.html.
    explanation: ClassVar[str]

    @property
    def detail(self) -> str | None:
        """
        The underlying error that this exception was raised from, if any.
        """
        if self.__cause__ is None:
            return None
        if str(self.__cause__):
            return f"{type(self.__cause__).__name__}: {self.__cause__}"
        return type(self.__cause__).__name__


class InvalidRequestError(BaseProxyError):
    """
    The request to the portal was malformed.
    """

    http_status = 400
    title = "Invalid Request"
    explanation = "No connection to the remote server was attempted."


class RequestBlockedError(BaseProxyError):
    """
    The portal refused to make the request.
    """

    http_status = 403
    title = "Request Blocked"
    explanation = "No connection to the remote server was attempted."


class UpstreamConnectionError(BaseProxyError):
    """
    The connection to the proxied server could not be established.
    """

    http_status = 502
    title = "Gateway Error"
    explanation = "The request to the remote server could not be completed."


class UpstreamTimeoutError(BaseProxyError):
    """
    The proxied server took too long to respond.
    """

    http_status = 504
    title = "Gateway Timeout"
    explanation = "The request to the remote server could not be completed."


class UpstreamResponseError(BaseProxyError):
    """
    The proxied server responded with something unparseable.
    """

    http_status = 502
    title = "Gateway Error"
    explanation = "The request to the remote server could not be completed."
