#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

uv sync

# Initialize the sqlite database
uv run python -m geminiportal.db

echo "Bootstrap completed!"
echo "To launch the server, run:"
echo "tools/quart run"
